### ISSUE TITLE
3.8 typing相关支持

### ISSUE THREAD

**Issue by ElainaFanBoy** [CofinCup/nonebot-plugin-todo-nlp#3]
jionlp - jio.help() is for searching how to use jio functions.
         - Or browse `https://github.com/dongrixinyu/JioNLP` to get help.
         - Or browse `http://www.jionlp.com` to try online functions.
 jiojio - http://www.jionlp.com/jionlp_online/cws_pos is available for online use.
D:\Desktop\0\ruanjian\Hinata-Bot-main\Hinata-Bot-main\src\plugins\nonebot_plugin_todo_nlp\config.py:4: FutureWarning: aliases are no longer used by BaseSettings to define which environment variables to read. Instead use the "env" field setting. See https://pydantic-docs.helpmanual.io/usage/settings/#environment-variable-names
  class Time(BaseSettings):

09-03 22:07:59 [ERROR] nonebot | Failed to import "nonebot_plugin_todo_nlp"
Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    nonebot.load_plugins("src/plugins")
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
 File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Desktop\0\ruanjian\Hinata-Bot-main\Hinata-Bot-main\src\plugins\nonebot_plugin_todo_nlp\__init__.py", line 1, in <module>
    from .todo_manage import add_todo, finish_todo, remove_todo, change_todo_time, get_todo_pic
  File "D:\Desktop\0\ruanjian\Hinata-Bot-main\Hinata-Bot-main\src\plugins\nonebot_plugin_todo_nlp\todo_manage.py", line 12, in <module>
    from .config import Config
  File "D:\Desktop\0\ruanjian\Hinata-Bot-main\Hinata-Bot-main\src\plugins\nonebot_plugin_todo_nlp\config.py", line 14, in <module>
    class Config(BaseSettings):
  File "D:\Desktop\0\ruanjian\Hinata-Bot-main\Hinata-Bot-main\src\plugins\nonebot_plugin_todo_nlp\config.py", line 18, in Config
    todo_users: list[int] = []
TypeError: 'type' object is not subscriptable

报错内容如上 ，萌新表示看不懂（：0）

**Comment by CofinCup** [comment]
没配置todo_users
见readme中的[配置方法](https://github.com/CofinCup/nonebot-plugin-todo-nlp#%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95)

**Comment by ElainaFanBoy** [comment]
> 没配置todo_users 见readme中的[配置方法](https://github.com/CofinCup/nonebot-plugin-todo-nlp#%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95)

我只配置在.env文件里了，运行就是这样，config.py也是按这样配置吗（我先试试）

**Comment by ElainaFanBoy** [comment]
> 没配置todo_users 见readme中的[配置方法](https://github.com/CofinCup/nonebot-plugin-todo-nlp#%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95)

还是不行，我在config.py里填了还是报错

  File "D:\Desktop\0\ruanjian\Hinata-Bot-main\Hinata-Bot-main\src\plugins\nonebot_plugin_todo_nlp\__init__.py", line 1, in <module>
    from .todo_manage import add_todo, finish_todo, remove_todo, change_todo_time, get_todo_pic
  File "D:\Desktop\0\ruanjian\Hinata-Bot-main\Hinata-Bot-main\src\plugins\nonebot_plugin_todo_nlp\todo_manage.py", line 12, in <module>
    from .config import Config
  File "D:\Desktop\0\ruanjian\Hinata-Bot-main\Hinata-Bot-main\src\plugins\nonebot_plugin_todo_nlp\config.py", line 14, in <module>
    class Config(BaseSettings):
  File "D:\Desktop\0\ruanjian\Hinata-Bot-main\Hinata-Bot-main\src\plugins\nonebot_plugin_todo_nlp\config.py", line 18, in Config
    todo_users: list[int] = ['712111161']
TypeError: 'type' object is not subscriptable

**Comment by CofinCup** [comment]
……我猜到问题了，但是我不知道这个问题为啥会出现，我想想。
int被识别成下标了。
你把"[int]"去掉试试

**Comment by ElainaFanBoy** [comment]
> ……我猜到问题了，但是我不知道这个问题为啥会出现，我想想。 int被识别成下标了。

大佬辛苦了，我等你下次update修复吧（lol）

**Comment by CofinCup** [comment]
我这边typing是可以正常识别的，但不知道为啥你那边typings没管用（

**Comment by ElainaFanBoy** [comment]
> ……我猜到问题了，但是我不知道这个问题为啥会出现，我想想。 int被识别成下标了。 你把"[int]"去掉试试

[int]去掉没报错了，然后[Time()]也要去掉吗

    todo_send_time: list[Time()] = [{"HOUR":8,"MINUTE":0},{"HOUR":19,"MINUTE":0}]
TypeError: 'type' object is not subscriptable

**Comment by CofinCup** [comment]
> > ……我猜到问题了，但是我不知道这个问题为啥会出现，我想想。 int被识别成下标了。 你把"[int]"去掉试试
> 
> [int]去掉没报错了，然后[Time()]也要去掉吗
> 
> ```
> todo_send_time: list[Time()] = [{"HOUR":8,"MINUTE":0},{"HOUR":19,"MINUTE":0}]
> ```
> 
> TypeError: 'type' object is not subscriptable

一样

**Comment by ElainaFanBoy** [comment]
> 我这边typing是可以正常识别的，但不知道为啥你那边typings没管用（

是不是跟py版本有关系

**Comment by ElainaFanBoy** [comment]
> > > ……我猜到问题了，但是我不知道这个问题为啥会出现，我想想。 int被识别成下标了。 你把"[int]"去掉试试
> > 
> > 
> > [int]去掉没报错了，然后[Time()]也要去掉吗
> > ```
> > todo_send_time: list[Time()] = [{"HOUR":8,"MINUTE":0},{"HOUR":19,"MINUTE":0}]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > TypeError: 'type' object is not subscriptable
> 
> 一样

又报错了

  File "D:\Desktop\0\ruanjian\Hinata-Bot-main\Hinata-Bot-main\src\plugins\nonebot_plugin_todo_nlp\todo_manage.py", line 136, in <module>
    scheduler.add_job(send_todo, "cron", hour=_time.hour, minute=_time.minute, id=str(f"send_todo_for_{index}"))
AttributeError: 'dict' object has no attribute 'hour'

**Comment by CofinCup** [comment]
> > > > ……我猜到问题了，但是我不知道这个问题为啥会出现，我想想。 int被识别成下标了。 你把"[int]"去掉试试
> > > 
> > > 
> > > [int]去掉没报错了，然后[Time()]也要去掉吗
> > > ```
> > > todo_send_time: list[Time()] = [{"HOUR":8,"MINUTE":0},{"HOUR":19,"MINUTE":0}]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > TypeError: 'type' object is not subscriptable
> > 
> > 
> > 一样
> 
> 又报错了
> 
> File "D:\Desktop\0\ruanjian\Hinata-Bot-main\Hinata-Bot-main\src\plugins\nonebot_plugin_todo_nlp\todo_manage.py", line 136, in scheduler.add_job(send_todo, "cron", hour=_time.hour, minute=_time.minute, id=str(f"send_todo_for_{index}")) AttributeError: 'dict' object has no attribute 'hour'

config这段抄的leetcode插件代码（
还真没细想过，3.8稳定还是等下个版本吧（

**Comment by ElainaFanBoy** [comment]
> > > > > ……我猜到问题了，但是我不知道这个问题为啥会出现，我想想。 int被识别成下标了。 你把"[int]"去掉试试
> > > > 
> > > > 
> > > > [int]去掉没报错了，然后[Time()]也要去掉吗
> > > > ```
> > > > todo_send_time: list[Time()] = [{"HOUR":8,"MINUTE":0},{"HOUR":19,"MINUTE":0}]
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > TypeError: 'type' object is not subscriptable
> > > 
> > > 
> > > 一样
> > 
> > 
> > 又报错了
> > File "D:\Desktop\0\ruanjian\Hinata-Bot-main\Hinata-Bot-main\src\plugins\nonebot_plugin_todo_nlp\todo_manage.py", line 136, in scheduler.add_job(send_todo, "cron", hour=_time.hour, minute=_time.minute, id=str(f"send_todo_for_{index}")) AttributeError: 'dict' object has no attribute 'hour'
> 
> config这段抄的leetcode插件代码（ 还真没细想过，3.8稳定还是等下个版本吧（

好的，坐等下次更新（辛苦了

**Comment by CofinCup** [comment]
typing相关问题已修复，目前测试v0.1.7在3.8.13版本下可运行

**Comment by ElainaFanBoy** [comment]
> typing相关问题已修复，目前测试v0.1.7在3.8.13版本下可运行

好的，我回家试试我3.8.5能不能使用

**Comment by CofinCup** [comment]
能正常跑了吗，能的话我close了

**Comment by ElainaFanBoy** [comment]
> 能正常跑了吗，能的话我close了

可以了，感谢
