### ISSUE TITLE
报未实现错误

### ISSUE THREAD

**Issue by flyweb291** [CofinCup/nonebot-plugin-todo-nlp#5]
D:\Apps\miniconda3\envs\nb2\python.exe E:\Dev_env\PyCharmProjects\nb2\nb2\bot.py 
10-17 00:51:34 [SUCCESS] nonebot | NoneBot is initializing...
10-17 00:51:34 [INFO] nonebot | Current Env: dev
10-17 00:51:34 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True}
10-17 00:51:34 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
10-17 00:51:34 [SUCCESS] nonebot | Succeeded to import "echo"
10-17 00:51:34 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
# jionlp - `https://github.com/dongrixinyu/JioNLP` provides detailed instruction.
# jiojio - `http://www.jionlp.com/jionlp_online/cws_pos` is available for online use.
D:\Apps\miniconda3\envs\nb2\lib\site-packages\nonebot_plugin_todo_nlp\config.py:4: FutureWarning: aliases are no longer used by BaseSettings to define which environment variables to read. Instead use the "env" field setting. See https://pydantic-docs.helpmanual.io/usage/settings/#environment-variable-names
  class Time(BaseSettings):
10-17 00:51:36 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_todo_nlp"
10-17 00:51:36 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
10-17 00:51:36 [SUCCESS] nonebot | Running NoneBot...
10-17 00:51:36 [DEBUG] nonebot | Loaded adapters: OneBot V11
10-17 00:51:36 [INFO] uvicorn | Will watch for changes in these directories: ['E:\\Dev_env\\PyCharmProjects\\nb2\\nb2']
10-17 00:51:36 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
10-17 00:51:36 [INFO] uvicorn | Started reloader process [20272] using WatchFiles
10-17 00:51:36 [SUCCESS] nonebot | NoneBot is initializing...
10-17 00:51:36 [INFO] nonebot | Current Env: dev
10-17 00:51:36 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True}
10-17 00:51:37 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
10-17 00:51:37 [SUCCESS] nonebot | Succeeded to import "echo"
10-17 00:51:37 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
# jionlp - `https://github.com/dongrixinyu/JioNLP` provides detailed instruction.
# jiojio - `http://www.jionlp.com/jionlp_online/cws_pos` is available for online use.
D:\Apps\miniconda3\envs\nb2\lib\site-packages\nonebot_plugin_todo_nlp\config.py:4: FutureWarning: aliases are no longer used by BaseSettings to define which environment variables to read. Instead use the "env" field setting. See https://pydantic-docs.helpmanual.io/usage/settings/#environment-variable-names
  class Time(BaseSettings):
10-17 00:51:38 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_todo_nlp"
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.run() done, defined at D:\Apps\miniconda3\envs\nb2\lib\site-packages\playwright\_impl\_connection.py:217> exception=NotImplementedError()>
Traceback (most recent call last):
  File "D:\Apps\miniconda3\envs\nb2\lib\site-packages\playwright\_impl\_connection.py", line 224, in run
    await self._transport.connect()
  File "D:\Apps\miniconda3\envs\nb2\lib\site-packages\playwright\_impl\_transport.py", line 133, in connect
    raise exc
  File "D:\Apps\miniconda3\envs\nb2\lib\site-packages\playwright\_impl\_transport.py", line 121, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "D:\Apps\miniconda3\envs\nb2\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "D:\Apps\miniconda3\envs\nb2\lib\asyncio\base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "D:\Apps\miniconda3\envs\nb2\lib\asyncio\base_events.py", line 491, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
10-17 00:51:39 [INFO] uvicorn | Started server process [19532]
10-17 00:51:39 [INFO] uvicorn | Waiting for application startup.
10-17 00:51:39 [INFO] nonebot_plugin_apscheduler | Scheduler Started
10-17 00:51:39 [ERROR] uvicorn | Traceback (most recent call last):
  File "D:\Apps\miniconda3\envs\nb2\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "D:\Apps\miniconda3\envs\nb2\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "D:\Apps\miniconda3\envs\nb2\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "D:\Apps\miniconda3\envs\nb2\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 25, in init
    browser = await get_browser(**kwargs)
  File "D:\Apps\miniconda3\envs\nb2\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 59, in get_browser
    return _browser or await init(**kwargs)
  File "D:\Apps\miniconda3\envs\nb2\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 36, in init
    _playwright = await async_playwright().start()
  File "D:\Apps\miniconda3\envs\nb2\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "D:\Apps\miniconda3\envs\nb2\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "D:\Apps\miniconda3\envs\nb2\lib\site-packages\playwright\_impl\_connection.py", line 224, in run
    await self._transport.connect()
  File "D:\Apps\miniconda3\envs\nb2\lib\site-packages\playwright\_impl\_transport.py", line 133, in connect
    raise exc
  File "D:\Apps\miniconda3\envs\nb2\lib\site-packages\playwright\_impl\_transport.py", line 121, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "D:\Apps\miniconda3\envs\nb2\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "D:\Apps\miniconda3\envs\nb2\lib\asyncio\base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "D:\Apps\miniconda3\envs\nb2\lib\asyncio\base_events.py", line 491, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

10-17 00:51:39 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by CofinCup** [comment]
去nonebot下查了Task exception was never retrieved相关的问题，我猜测是你在win下跑并且没有把FASTAPI_RELOAD改为false

**Comment by CofinCup** [comment]
请问修改了fastapi相关设置之后正常了吗？正常的话我就把issue关了（？）
